[package]
name = "veri-asm"
version = "0.1.0"
edition = "2021"

[lib]
name = "veriasm"

[[bin]]
name = "dis"

[[bin]]
name = "armv7m"

[dependencies]
capstone = "0.12.0"
elf = "0.7.4"
flux-rs = { git  = "https://github.com/flux-rs/flux.git" }

[package.metadata.flux]
enabled = true
